source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'ruby-debug'
gem 'mechanize'
gem 'delayed_job'
gem 'delayed_job_admin', :git => 'git://github.com/woto/delayed_job_admin.git'
gem 'simple_form'
gem 'formtastic'
gem 'rails-i18n'
gem 'simple-navigation', :git => 'https://github.com/andi/simple-navigation.git'
gem 'haml'
gem 'hpricot'
gem 'ruby_parser'
gem 'compass', '~> 0.12.alpha'
